[package]
name = "lietuviu-zodynas"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.51"
either = "1.15.0"
html_parser = "0.7.0"
tabled = "0.20.0"
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
